### ISSUE TITLE
Create knowledge sharing platform for data scientists, analysts, and product

### ISSUE THREAD

**Issue by Chengyingsjtu** [happyelementsai/Knowledge-Repo#1]
As we run analysis from data scientists, analysts, and product team, we want to scale our ability to share our research findings and techniques. It used to be the case that we summarize our results in slides, google docs, python notebooks, in which case we will take lots of effort and time to find the relevant resources. 

Airbnb created an open-source system [Knowledge Repo](https://knowledge-repo.readthedocs.io/en/latest/) that allows for efficient knowledge sharing by combining results reproducibility, code quality, easy navigation, and learning together. 

@hushaoqing @jinkun-Tian Let's test Knowledge Repo and see how it works. Thanks!

cc: @richardchen100 @reinhouthooft

**Comment by jinkun-Tian** [comment]
#### System Structure
![image](https://user-images.githubusercontent.com/57387662/83973733-ed145d00-a91a-11ea-8742-0ac6f31c464d.png)

#### Github address:
https://github.com/happyelementsai/knowledge_repo.git

#### Server address:
http://120.77.249.159:6500/feed

**Comment by jinkun-Tian** [comment]
### 1. How to use knowledge repo in client

1.1 install knowledge repo.

```
pip install --upgrade "knowledge-repo[all]"
```

1.2 Clone git project to local

```
git clone https://github.com/happyelementsai/knowledge_repo.git
```

1.3 Init knowledge repo

```
knowledge_repo --repo git:///<repo_path> init
```

1.4 Create py/md 

```
knowledge_repo --repo <repo_path> create md my_first_knowledge_post.md
```

1.5 Add the document to your project

```
knowledge_repo --repo <repo_path> add my_first_knowledge_post.md -p project/first
```

1.6 Review the page

```
knowledge_repo --repo <repo_path> preview project/first
```

1.7 Submit the document to git

```
knowledge_repo --repo <repo_path> submit project/first
```

### 2. Merge the branch to master in github

### 3. Pull the change in server

**Comment by jinkun-Tian** [comment]
Fix the bug when knowlege uses github login. Now we can login with github account. 
Otherwise,I change the port to 7000, which is the default port.
(http://120.77.249.159:7000/feed)
@Chengyingsjtu
